# This configuration is activated if you active the "dev" profile:
#   -Dspring.profiles.active=dev

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.zaxxer.hikari: ERROR
    fr.ciadlab: DEBUG
  file:
    path: /path/to/root/folder

spring:
  sql:
    init:
      platform: derby
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.StandardJtaPlatformResolver
        format-sql: true
        auto-quote-keyword: true
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            create-database-schemas: true
            database:
              action: create
            scripts:
              action: create
              create-target: /path/to/root/folder/schema-derby-gen.sql

  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:directory:/path/to/root/folder/db;create=true
    generate-unique-name: false
    username: sa
    password:

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    serialization:
      indent-output: true

server:
  servlet:
    context-path: /LabManagerApi
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    logfile:
      enabled: true
      external-file: /path/to/root/folder/LabManagerApi.log
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"
  security:
    enabled: false
    roles: ROLE_ADMIN

labmanager:
  debug: true
  default-organization: NAME_OF_ORGANIZATION
  default-super-organization: NAME_OF_ENCLOSING_ORGANIZATION
  default-lear-organization: NAME_OF_ENCLOSING_ORGANIZATION
  init:
    enable: true
    data-source: /path/to/root/folder
  file:
    upload-directory: /path/to/root/folder
    temp-directory: /path/to/root/folder/tmp
  web:
    publish-resources: /path/to/root/folder/Downloadables/
    help-url: http://localhost:8080/docs/
  security:
    username-key: UUID
