# This configuration is activated if you active the "dev" profile:
#   -Dspring.profiles.active=dev

logging:
  level:
    fr.ciadlab: DEBUG
  file:
    path: /tmp/ciadlab

spring:
  datasource:
    # H2 database
    url: jdbc:h2:file:/tmp/ciadlab/db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      # Lines dedicated only to generating the SQL script file, it is not applied to the DB. These are from JPA, not from Hibernate
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: schema-h2-gen.sql
              create-source: metadata

server:
  servlet:
    context-path: /LabManagerApi
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    logfile:
      # Path to the log file
      external-file: /tmp/ciadlab/LabManagerApi.log

labmanager:
  default-organization: LABORATOIRYNAME
  default-super-organization: UNIVERSITYNAME
  default-lear-organization: UNIVERSITYNAME
  file:
    upload-directory: /tmp/ciadlab
    tmp-directory: /tmp/ciadlab
  web:
    publish-resources: /tmp/ciadlab/Downloadables/
    help-url: https://www.ciad-lab.fr/docs/
  debug: true
  security:
    username-key: some-key
  init:
    data-source: /tmp/ciadlab/data.json
    enable: true
