# This configuration is activated if you active the "dev" profile:
#   -Dspring.profiles.active=dev

logging:
  level:
    fr.ciadlab: DEBUG
  file:
    path: /some_path/labmanager-tmp

spring:
  datasource:
    url: jdbc:h2:file:/some_path/labmanager-tmp/db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /LabManagerApi
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    logfile:
      # Path to the log file
      external-file: /some_path/labmanager-tmp/LabManagerApi.log

labmanager:
  default-organization: CIAD
  default-super-organization: UTBM
  default-lear-organization: UTBM
  file:
    upload-directory: /some_path/labmanager-tmp
    temp-directory: /some_path/labmanager-tmp
  web:
    publish-resources: /some_path/labmanager-tmp/Downloadables/
    help-url: https://www.ciad-lab.fr/docs/
  debug: true
  security:
    username-key: some-key
  init:
    data-source: /some_path/labmanager/labmanager-2/src/main/resources/data.json
    enable: true
