logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    fr.ciadlab: INFO
  file:
    path: /var/log/tomcat9

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
        auto_quote_keyword: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.StandardJtaPlatformResolver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhsome_path/labmanager/labmanager-2/src/main/resourcesost:3306/labmanager?serverTimezone=UTC
    username: ciadlabwpbdd
    password: ci@dlAbpas$

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /LabManagerApi
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoint:
    logfile:
      enabled: true
      external-file: /var/log/tomcat9/LabManagerApi.log
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"
  security:
    enabled: false
    roles: ROLE_ADMIN

labmanager:
  default-organization: CIAD
  default-super-organization: UTBM
  default-lear-organization: UTBM
  init:
    enable: true
    data-source: /var/www/ciad-lab.fr/
  file:
    upload-directory: /var/www/ciad-lab.fr/
    temp-directory: /tmp/ciadlab/
  web:
    publish-resources: /var/www/ciad-lab.fr/Downloadables/
    help-url: https://www.ciad-lab.fr/docs/
  debug: false
  security:
    username-key: 27b0e0c60fec4b60
  splash-screen: "\n
    .  _____ _____          _____    _           _     \n
    . / ____|_   _|   /\\   |  __ \\  | |         | |    \n
    .| |      | |    /  \\  | |  | | | |     __ _| |__  \n
    .| |      | |   / /\\ \\ | |  | | | |    / _` | '_ \\ \n
    .| |____ _| |_ / ____ \\| |__| | | |___| (_| | |_) |\n
    . \\_____|_____/_/    \\_\\_____/  |______\\__,_|_.__/ \n
    .|  \\/  |                                          \n
    .| \\  / | __ _ _ __   __ _  __ _  ___ _ __         \n
    .| |\\/| |/ _` | '_ \\ / _` |/ _` |/ _ \\ '__|        \n
    .| |  | | (_| | | | | (_| | (_| |  __/ |           \n
    .|_|  |_|\\__,_|_| |_|\\__,_|\\__, |\\___|_|           \n
    .                           __/ |                  \n
    .                          |___/                   "
